/**
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 August, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body17 model module.
* @module model/Body17
* @version 1.0.0
*/
export default class Body17 {
    /**
    * Constructs a new <code>Body17</code>.
    * @alias module:model/Body17
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body17</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body17} obj Optional instance to populate.
    * @return {module:model/Body17} The populated <code>Body17</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body17();
                        
            
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('major')) {
                obj['major'] = ApiClient.convertToType(data['major'], 'Number');
            }
            if (data.hasOwnProperty('minor')) {
                obj['minor'] = ApiClient.convertToType(data['minor'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Desired UUID of the beacon. If the value is set to null it will reset to Dashboard's automatically generated value.
    * @member {String} uuid
    */
    'uuid' = undefined;
    /**
    * Desired major value of the beacon. If the value is set to null it will reset to Dashboard's automatically generated value.
    * @member {Number} major
    */
    'major' = undefined;
    /**
    * Desired minor value of the beacon. If the value is set to null it will reset to Dashboard's automatically generated value.
    * @member {Number} minor
    */
    'minor' = undefined;




}
