/**
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 August, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrganizationsorganizationIdappliancevpnvpnFirewallRulesRules from './OrganizationsorganizationIdappliancevpnvpnFirewallRulesRules';

/**
* The Body128 model module.
* @module model/Body128
* @version 1.0.0
*/
export default class Body128 {
    /**
    * Constructs a new <code>Body128</code>.
    * @alias module:model/Body128
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body128</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body128} obj Optional instance to populate.
    * @return {module:model/Body128} The populated <code>Body128</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body128();
                        
            
            if (data.hasOwnProperty('rules')) {
                obj['rules'] = ApiClient.convertToType(data['rules'], [OrganizationsorganizationIdappliancevpnvpnFirewallRulesRules]);
            }
            if (data.hasOwnProperty('syslogDefaultRule')) {
                obj['syslogDefaultRule'] = ApiClient.convertToType(data['syslogDefaultRule'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * An ordered array of the firewall rules (not including the default rule)
    * @member {Array.<module:model/OrganizationsorganizationIdappliancevpnvpnFirewallRulesRules>} rules
    */
    'rules' = undefined;
    /**
    * Log the special default rule (boolean value - enable only if you've configured a syslog server) (optional)
    * @member {Boolean} syslogDefaultRule
    */
    'syslogDefaultRule' = undefined;




}
