/**
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 August, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body73 model module.
* @module model/Body73
* @version 1.0.0
*/
export default class Body73 {
    /**
    * Constructs a new <code>Body73</code>.
    * @alias module:model/Body73
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body73</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body73} obj Optional instance to populate.
    * @return {module:model/Body73} The populated <code>Body73</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body73();
                        
            
            if (data.hasOwnProperty('wifiMac')) {
                obj['wifiMac'] = ApiClient.convertToType(data['wifiMac'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('serial')) {
                obj['serial'] = ApiClient.convertToType(data['serial'], 'String');
            }
            if (data.hasOwnProperty('pin')) {
                obj['pin'] = ApiClient.convertToType(data['pin'], 'Number');
            }
        }
        return obj;
    }

    /**
    * The wifiMac of the device to be wiped.
    * @member {String} wifiMac
    */
    'wifiMac' = undefined;
    /**
    * The id of the device to be wiped.
    * @member {String} id
    */
    'id' = undefined;
    /**
    * The serial of the device to be wiped.
    * @member {String} serial
    */
    'serial' = undefined;
    /**
    * The pin number (a six digit value) for wiping a macOS device. Required only for macOS devices.
    * @member {Number} pin
    */
    'pin' = undefined;




}
