/**
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 August, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body70 model module.
* @module model/Body70
* @version 1.0.0
*/
export default class Body70 {
    /**
    * Constructs a new <code>Body70</code>.
    * @alias module:model/Body70
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Body70</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body70} obj Optional instance to populate.
    * @return {module:model/Body70} The populated <code>Body70</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body70();
                        
            
            if (data.hasOwnProperty('localStatusPageEnabled')) {
                obj['localStatusPageEnabled'] = ApiClient.convertToType(data['localStatusPageEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('remoteStatusPageEnabled')) {
                obj['remoteStatusPageEnabled'] = ApiClient.convertToType(data['remoteStatusPageEnabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * Enables / disables the local device status pages (<a target='_blank' href='http://my.meraki.com/'>my.meraki.com, </a><a target='_blank' href='http://ap.meraki.com/'>ap.meraki.com, </a><a target='_blank' href='http://switch.meraki.com/'>switch.meraki.com, </a><a target='_blank' href='http://wired.meraki.com/'>wired.meraki.com</a>). Optional (defaults to false)
    * @member {Boolean} localStatusPageEnabled
    */
    'localStatusPageEnabled' = undefined;
    /**
    * Enables / disables access to the device status page (<a target='_blank'>http://[device's LAN IP])</a>. Optional. Can only be set if localStatusPageEnabled is set to true
    * @member {Boolean} remoteStatusPageEnabled
    */
    'remoteStatusPageEnabled' = undefined;




}
