/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MerakiDashboardApi) {
      root.MerakiDashboardApi = {};
    }
    root.MerakiDashboardApi.NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories = factory(root.MerakiDashboardApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories model module.
   * @module model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories</code>.
   * Settings for blocked URL categories
   * @alias module:model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories} obj Optional instance to populate.
   * @return {module:model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories} The populated <code>NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('settings'))
        obj.settings = ApiClient.convertToType(data['settings'], 'String');
      if (data.hasOwnProperty('categories'))
        obj.categories = ApiClient.convertToType(data['categories'], ['String']);
    }
    return obj;
  }

  /**
   * How URL categories are applied. Can be 'network default', 'append' or 'override'.
   * @member {module:model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories.SettingsEnum} settings
   */
  exports.prototype.settings = undefined;

  /**
   * A list of URL categories to block
   * @member {Array.<String>} categories
   */
  exports.prototype.categories = undefined;


  /**
   * Allowed values for the <code>settings</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SettingsEnum = {
    /**
     * value: "network default"
     * @const
     */
    networkDefault: "network default",

    /**
     * value: "append"
     * @const
     */
    append: "append",

    /**
     * value: "override"
     * @const
     */
    override: "override"
  };

  return exports;

}));
