/**
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 August, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimitsBandwidthLimits from './NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimitsBandwidthLimits';

/**
* The NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits model module.
* @module model/NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits
* @version 1.0.0
*/
export default class NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits {
    /**
    * Constructs a new <code>NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits</code>.
    *     An object describing the bandwidth settings for your rule. 
    * @alias module:model/NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits} obj Optional instance to populate.
    * @return {module:model/NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits} The populated <code>NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimits();
                        
            
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = ApiClient.convertToType(data['settings'], 'String');
            }
            if (data.hasOwnProperty('bandwidthLimits')) {
                obj['bandwidthLimits'] = NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimitsBandwidthLimits.constructFromObject(data['bandwidthLimits']);
            }
        }
        return obj;
    }

    /**
    * How bandwidth limits are applied by your rule. Can be one of 'network default', 'ignore' or 'custom'.
    * @member {String} settings
    */
    'settings' = undefined;
    /**
    * @member {module:model/NetworksnetworkIdappliancetrafficShapingrulesPerClientBandwidthLimitsBandwidthLimits} bandwidthLimits
    */
    'bandwidthLimits' = undefined;




}
