/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MerakiDashboardApi) {
      root.MerakiDashboardApi = {};
    }
    root.MerakiDashboardApi.NetworksnetworkIdappliancevpnsiteToSiteVpnHubs = factory(root.MerakiDashboardApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The NetworksnetworkIdappliancevpnsiteToSiteVpnHubs model module.
   * @module model/NetworksnetworkIdappliancevpnsiteToSiteVpnHubs
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>NetworksnetworkIdappliancevpnsiteToSiteVpnHubs</code>.
   * @alias module:model/NetworksnetworkIdappliancevpnsiteToSiteVpnHubs
   * @class
   * @param hubId {String} The network ID of the hub.
   */
  var exports = function(hubId) {
    this.hubId = hubId;
  };

  /**
   * Constructs a <code>NetworksnetworkIdappliancevpnsiteToSiteVpnHubs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NetworksnetworkIdappliancevpnsiteToSiteVpnHubs} obj Optional instance to populate.
   * @return {module:model/NetworksnetworkIdappliancevpnsiteToSiteVpnHubs} The populated <code>NetworksnetworkIdappliancevpnsiteToSiteVpnHubs</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('hubId'))
        obj.hubId = ApiClient.convertToType(data['hubId'], 'String');
      if (data.hasOwnProperty('useDefaultRoute'))
        obj.useDefaultRoute = ApiClient.convertToType(data['useDefaultRoute'], 'Boolean');
    }
    return obj;
  }

  /**
   * The network ID of the hub.
   * @member {String} hubId
   */
  exports.prototype.hubId = undefined;

  /**
   * Only valid in 'spoke' mode. Indicates whether default route traffic should be sent to this hub.
   * @member {Boolean} useDefaultRoute
   */
  exports.prototype.useDefaultRoute = undefined;

  return exports;

}));
