/**
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 August, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsCellular from './NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsCellular';
import NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsWan1 from './NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsWan1';
import NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsWan2 from './NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsWan2';

/**
* The NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits model module.
* @module model/NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits
* @version 1.0.0
*/
export default class NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits {
    /**
    * Constructs a new <code>NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits</code>.
    * A mapping of uplinks to their bandwidth settings (be sure to check which uplinks are supported for your network)
    * @alias module:model/NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits} obj Optional instance to populate.
    * @return {module:model/NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits} The populated <code>NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimits();
                        
            
            if (data.hasOwnProperty('wan1')) {
                obj['wan1'] = NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsWan1.constructFromObject(data['wan1']);
            }
            if (data.hasOwnProperty('wan2')) {
                obj['wan2'] = NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsWan2.constructFromObject(data['wan2']);
            }
            if (data.hasOwnProperty('cellular')) {
                obj['cellular'] = NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsCellular.constructFromObject(data['cellular']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsWan1} wan1
    */
    'wan1' = undefined;
    /**
    * @member {module:model/NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsWan2} wan2
    */
    'wan2' = undefined;
    /**
    * @member {module:model/NetworksnetworkIdappliancetrafficShapinguplinkBandwidthBandwidthLimitsCellular} cellular
    */
    'cellular' = undefined;




}
