/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns', 'model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories', 'model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns'), require('./NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories'), require('./NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns'));
  } else {
    // Browser globals (root is window)
    if (!root.MerakiDashboardApi) {
      root.MerakiDashboardApi = {};
    }
    root.MerakiDashboardApi.NetworksnetworkIdgroupPoliciesContentFiltering = factory(root.MerakiDashboardApi.ApiClient, root.MerakiDashboardApi.NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns, root.MerakiDashboardApi.NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories, root.MerakiDashboardApi.NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns);
  }
}(this, function(ApiClient, NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns, NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories, NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns) {
  'use strict';

  /**
   * The NetworksnetworkIdgroupPoliciesContentFiltering model module.
   * @module model/NetworksnetworkIdgroupPoliciesContentFiltering
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>NetworksnetworkIdgroupPoliciesContentFiltering</code>.
   * The content filtering settings for your group policy
   * @alias module:model/NetworksnetworkIdgroupPoliciesContentFiltering
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>NetworksnetworkIdgroupPoliciesContentFiltering</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NetworksnetworkIdgroupPoliciesContentFiltering} obj Optional instance to populate.
   * @return {module:model/NetworksnetworkIdgroupPoliciesContentFiltering} The populated <code>NetworksnetworkIdgroupPoliciesContentFiltering</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('allowedUrlPatterns'))
        obj.allowedUrlPatterns = NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns.constructFromObject(data['allowedUrlPatterns']);
      if (data.hasOwnProperty('blockedUrlPatterns'))
        obj.blockedUrlPatterns = NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns.constructFromObject(data['blockedUrlPatterns']);
      if (data.hasOwnProperty('blockedUrlCategories'))
        obj.blockedUrlCategories = NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories.constructFromObject(data['blockedUrlCategories']);
    }
    return obj;
  }

  /**
   * @member {module:model/NetworksnetworkIdgroupPoliciesContentFilteringAllowedUrlPatterns} allowedUrlPatterns
   */
  exports.prototype.allowedUrlPatterns = undefined;

  /**
   * @member {module:model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlPatterns} blockedUrlPatterns
   */
  exports.prototype.blockedUrlPatterns = undefined;

  /**
   * @member {module:model/NetworksnetworkIdgroupPoliciesContentFilteringBlockedUrlCategories} blockedUrlCategories
   */
  exports.prototype.blockedUrlCategories = undefined;

  return exports;

}));
