/**
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 August, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The NetworksnetworkIdwirelessrfProfilesFiveGhzSettings model module.
* @module model/NetworksnetworkIdwirelessrfProfilesFiveGhzSettings
* @version 1.0.0
*/
export default class NetworksnetworkIdwirelessrfProfilesFiveGhzSettings {
    /**
    * Constructs a new <code>NetworksnetworkIdwirelessrfProfilesFiveGhzSettings</code>.
    * Settings related to 5Ghz band
    * @alias module:model/NetworksnetworkIdwirelessrfProfilesFiveGhzSettings
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NetworksnetworkIdwirelessrfProfilesFiveGhzSettings</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NetworksnetworkIdwirelessrfProfilesFiveGhzSettings} obj Optional instance to populate.
    * @return {module:model/NetworksnetworkIdwirelessrfProfilesFiveGhzSettings} The populated <code>NetworksnetworkIdwirelessrfProfilesFiveGhzSettings</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworksnetworkIdwirelessrfProfilesFiveGhzSettings();
                        
            
            if (data.hasOwnProperty('maxPower')) {
                obj['maxPower'] = ApiClient.convertToType(data['maxPower'], 'Number');
            }
            if (data.hasOwnProperty('minPower')) {
                obj['minPower'] = ApiClient.convertToType(data['minPower'], 'Number');
            }
            if (data.hasOwnProperty('minBitrate')) {
                obj['minBitrate'] = ApiClient.convertToType(data['minBitrate'], 'Number');
            }
            if (data.hasOwnProperty('validAutoChannels')) {
                obj['validAutoChannels'] = ApiClient.convertToType(data['validAutoChannels'], ['Number']);
            }
            if (data.hasOwnProperty('channelWidth')) {
                obj['channelWidth'] = ApiClient.convertToType(data['channelWidth'], 'String');
            }
            if (data.hasOwnProperty('rxsop')) {
                obj['rxsop'] = ApiClient.convertToType(data['rxsop'], 'Number');
            }
        }
        return obj;
    }

    /**
    * Sets max power (dBm) of 5Ghz band. Can be integer between 8 and 30. Defaults to 30.
    * @member {Number} maxPower
    */
    'maxPower' = undefined;
    /**
    * Sets min power (dBm) of 5Ghz band. Can be integer between 8 and 30. Defaults to 8.
    * @member {Number} minPower
    */
    'minPower' = undefined;
    /**
    * Sets min bitrate (Mbps) of 5Ghz band. Can be one of '6', '9', '12', '18', '24', '36', '48' or '54'. Defaults to 12.
    * @member {Number} minBitrate
    */
    'minBitrate' = undefined;
    /**
    * Sets valid auto channels for 5Ghz band. Can be one of '36', '40', '44', '48', '52', '56', '60', '64', '100', '104', '108', '112', '116', '120', '124', '128', '132', '136', '140', '144', '149', '153', '157', '161' or '165'.Defaults to [36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165].
    * @member {Array.<Number>} validAutoChannels
    */
    'validAutoChannels' = undefined;
    /**
    * Sets channel width (MHz) for 5Ghz band. Can be one of 'auto', '20', '40' or '80'. Defaults to auto.
    * @member {String} channelWidth
    */
    'channelWidth' = undefined;
    /**
    *     The RX-SOP level controls the sensitivity of the radio. It is strongly recommended to use RX-SOP only after     consulting a wireless expert. RX-SOP can be configured in the range of -65 to -95 (dBm). A value of null will     reset this to the default. 
    * @member {Number} rxsop
    */
    'rxsop' = undefined;




}
