/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NetworksnetworkIdappliancefirewalloneToManyNatRulesPortRules'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NetworksnetworkIdappliancefirewalloneToManyNatRulesPortRules'));
  } else {
    // Browser globals (root is window)
    if (!root.MerakiDashboardApi) {
      root.MerakiDashboardApi = {};
    }
    root.MerakiDashboardApi.NetworksnetworkIdappliancefirewalloneToManyNatRulesRules = factory(root.MerakiDashboardApi.ApiClient, root.MerakiDashboardApi.NetworksnetworkIdappliancefirewalloneToManyNatRulesPortRules);
  }
}(this, function(ApiClient, NetworksnetworkIdappliancefirewalloneToManyNatRulesPortRules) {
  'use strict';

  /**
   * The NetworksnetworkIdappliancefirewalloneToManyNatRulesRules model module.
   * @module model/NetworksnetworkIdappliancefirewalloneToManyNatRulesRules
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>NetworksnetworkIdappliancefirewalloneToManyNatRulesRules</code>.
   * @alias module:model/NetworksnetworkIdappliancefirewalloneToManyNatRulesRules
   * @class
   * @param publicIp {String} The IP address that will be used to access the internal resource from the WAN
   * @param uplink {module:model/NetworksnetworkIdappliancefirewalloneToManyNatRulesRules.UplinkEnum} The physical WAN interface on which the traffic will arrive ('internet1' or, if available, 'internet2')
   * @param portRules {Array.<module:model/NetworksnetworkIdappliancefirewalloneToManyNatRulesPortRules>} An array of associated forwarding rules
   */
  var exports = function(publicIp, uplink, portRules) {
    this.publicIp = publicIp;
    this.uplink = uplink;
    this.portRules = portRules;
  };

  /**
   * Constructs a <code>NetworksnetworkIdappliancefirewalloneToManyNatRulesRules</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NetworksnetworkIdappliancefirewalloneToManyNatRulesRules} obj Optional instance to populate.
   * @return {module:model/NetworksnetworkIdappliancefirewalloneToManyNatRulesRules} The populated <code>NetworksnetworkIdappliancefirewalloneToManyNatRulesRules</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('publicIp'))
        obj.publicIp = ApiClient.convertToType(data['publicIp'], 'String');
      if (data.hasOwnProperty('uplink'))
        obj.uplink = ApiClient.convertToType(data['uplink'], 'String');
      if (data.hasOwnProperty('portRules'))
        obj.portRules = ApiClient.convertToType(data['portRules'], [NetworksnetworkIdappliancefirewalloneToManyNatRulesPortRules]);
    }
    return obj;
  }

  /**
   * The IP address that will be used to access the internal resource from the WAN
   * @member {String} publicIp
   */
  exports.prototype.publicIp = undefined;

  /**
   * The physical WAN interface on which the traffic will arrive ('internet1' or, if available, 'internet2')
   * @member {module:model/NetworksnetworkIdappliancefirewalloneToManyNatRulesRules.UplinkEnum} uplink
   */
  exports.prototype.uplink = undefined;

  /**
   * An array of associated forwarding rules
   * @member {Array.<module:model/NetworksnetworkIdappliancefirewalloneToManyNatRulesPortRules>} portRules
   */
  exports.prototype.portRules = undefined;


  /**
   * Allowed values for the <code>uplink</code> property.
   * @enum {String}
   * @readonly
   */
  exports.UplinkEnum = {
    /**
     * value: "internet1"
     * @const
     */
    internet1: "internet1",

    /**
     * value: "internet2"
     * @const
     */
    internet2: "internet2"
  };

  return exports;

}));
