/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MerakiDashboardApi) {
      root.MerakiDashboardApi = {};
    }
    root.MerakiDashboardApi.OrganizationsorganizationIdactionBatchesActions = factory(root.MerakiDashboardApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The OrganizationsorganizationIdactionBatchesActions model module.
   * @module model/OrganizationsorganizationIdactionBatchesActions
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>OrganizationsorganizationIdactionBatchesActions</code>.
   * @alias module:model/OrganizationsorganizationIdactionBatchesActions
   * @class
   * @param resource {String} Unique identifier for the resource to be acted on
   * @param operation {String} The operation to be used
   */
  var exports = function(resource, operation) {
    this.resource = resource;
    this.operation = operation;
  };

  /**
   * Constructs a <code>OrganizationsorganizationIdactionBatchesActions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrganizationsorganizationIdactionBatchesActions} obj Optional instance to populate.
   * @return {module:model/OrganizationsorganizationIdactionBatchesActions} The populated <code>OrganizationsorganizationIdactionBatchesActions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('resource'))
        obj.resource = ApiClient.convertToType(data['resource'], 'String');
      if (data.hasOwnProperty('operation'))
        obj.operation = ApiClient.convertToType(data['operation'], 'String');
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], Object);
    }
    return obj;
  }

  /**
   * Unique identifier for the resource to be acted on
   * @member {String} resource
   */
  exports.prototype.resource = undefined;

  /**
   * The operation to be used
   * @member {String} operation
   */
  exports.prototype.operation = undefined;

  /**
   * The body of the action
   * @member {Object} body
   */
  exports.prototype.body = undefined;

  return exports;

}));
