/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MerakiDashboardApi) {
      root.MerakiDashboardApi = {};
    }
    root.MerakiDashboardApi.UpdateNetworkSettings = factory(root.MerakiDashboardApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UpdateNetworkSettings model module.
   * @module model/UpdateNetworkSettings
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>UpdateNetworkSettings</code>.
   * @alias module:model/UpdateNetworkSettings
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UpdateNetworkSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateNetworkSettings} obj Optional instance to populate.
   * @return {module:model/UpdateNetworkSettings} The populated <code>UpdateNetworkSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('localStatusPageEnabled'))
        obj.localStatusPageEnabled = ApiClient.convertToType(data['localStatusPageEnabled'], 'Boolean');
      if (data.hasOwnProperty('remoteStatusPageEnabled'))
        obj.remoteStatusPageEnabled = ApiClient.convertToType(data['remoteStatusPageEnabled'], 'Boolean');
    }
    return obj;
  }

  /**
   * Enables / disables the local device status pages (<a target='_blank' href='http://my.meraki.com/'>my.meraki.com, </a><a target='_blank' href='http://ap.meraki.com/'>ap.meraki.com, </a><a target='_blank' href='http://switch.meraki.com/'>switch.meraki.com, </a><a target='_blank' href='http://wired.meraki.com/'>wired.meraki.com</a>). Optional (defaults to false)
   * @member {Boolean} localStatusPageEnabled
   */
  exports.prototype.localStatusPageEnabled = undefined;

  /**
   * Enables / disables access to the device status page (<a target='_blank'>http://[device's LAN IP])</a>. Optional. Can only be set if localStatusPageEnabled is set to true
   * @member {Boolean} remoteStatusPageEnabled
   */
  exports.prototype.remoteStatusPageEnabled = undefined;

  return exports;

}));
