/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NetworksnetworkIdswitchsettingsPowerExceptions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NetworksnetworkIdswitchsettingsPowerExceptions'));
  } else {
    // Browser globals (root is window)
    if (!root.MerakiDashboardApi) {
      root.MerakiDashboardApi = {};
    }
    root.MerakiDashboardApi.UpdateNetworkSwitchSettings = factory(root.MerakiDashboardApi.ApiClient, root.MerakiDashboardApi.NetworksnetworkIdswitchsettingsPowerExceptions);
  }
}(this, function(ApiClient, NetworksnetworkIdswitchsettingsPowerExceptions) {
  'use strict';

  /**
   * The UpdateNetworkSwitchSettings model module.
   * @module model/UpdateNetworkSwitchSettings
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>UpdateNetworkSwitchSettings</code>.
   * @alias module:model/UpdateNetworkSwitchSettings
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UpdateNetworkSwitchSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateNetworkSwitchSettings} obj Optional instance to populate.
   * @return {module:model/UpdateNetworkSwitchSettings} The populated <code>UpdateNetworkSwitchSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('vlan'))
        obj.vlan = ApiClient.convertToType(data['vlan'], 'Number');
      if (data.hasOwnProperty('useCombinedPower'))
        obj.useCombinedPower = ApiClient.convertToType(data['useCombinedPower'], 'Boolean');
      if (data.hasOwnProperty('powerExceptions'))
        obj.powerExceptions = ApiClient.convertToType(data['powerExceptions'], [NetworksnetworkIdswitchsettingsPowerExceptions]);
    }
    return obj;
  }

  /**
   * Management VLAN
   * @member {Number} vlan
   */
  exports.prototype.vlan = undefined;

  /**
   * The use Combined Power as the default behavior of secondary power supplies on supported devices.
   * @member {Boolean} useCombinedPower
   */
  exports.prototype.useCombinedPower = undefined;

  /**
   * Exceptions on a per switch basis to \"useCombinedPower\"
   * @member {Array.<module:model/NetworksnetworkIdswitchsettingsPowerExceptions>} powerExceptions
   */
  exports.prototype.powerExceptions = undefined;

  return exports;

}));
