/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MerakiDashboardApi) {
      root.MerakiDashboardApi = {};
    }
    root.MerakiDashboardApi.UpdateNetworkAppliancePort = factory(root.MerakiDashboardApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UpdateNetworkAppliancePort model module.
   * @module model/UpdateNetworkAppliancePort
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>UpdateNetworkAppliancePort</code>.
   * @alias module:model/UpdateNetworkAppliancePort
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UpdateNetworkAppliancePort</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateNetworkAppliancePort} obj Optional instance to populate.
   * @return {module:model/UpdateNetworkAppliancePort} The populated <code>UpdateNetworkAppliancePort</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('dropUntaggedTraffic'))
        obj.dropUntaggedTraffic = ApiClient.convertToType(data['dropUntaggedTraffic'], 'Boolean');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('vlan'))
        obj.vlan = ApiClient.convertToType(data['vlan'], 'Number');
      if (data.hasOwnProperty('allowedVlans'))
        obj.allowedVlans = ApiClient.convertToType(data['allowedVlans'], 'String');
      if (data.hasOwnProperty('accessPolicy'))
        obj.accessPolicy = ApiClient.convertToType(data['accessPolicy'], 'String');
    }
    return obj;
  }

  /**
   * The status of the port
   * @member {Boolean} enabled
   */
  exports.prototype.enabled = undefined;

  /**
   * Trunk port can Drop all Untagged traffic. When true, no VLAN is required. Access ports cannot have dropUntaggedTraffic set to true.
   * @member {Boolean} dropUntaggedTraffic
   */
  exports.prototype.dropUntaggedTraffic = undefined;

  /**
   * The type of the port: 'access' or 'trunk'.
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * Native VLAN when the port is in Trunk mode. Access VLAN when the port is in Access mode.
   * @member {Number} vlan
   */
  exports.prototype.vlan = undefined;

  /**
   * Comma-delimited list of the VLAN ID's allowed on the port, or 'all' to permit all VLAN's on the port.
   * @member {String} allowedVlans
   */
  exports.prototype.allowedVlans = undefined;

  /**
   * The name of the policy. Only applicable to Access ports. Valid values are: 'open', '8021x-radius', 'mac-radius', 'hybris-radius' for MX64 or Z3 or any MX supporting the per port authentication feature. Otherwise, 'open' is the only valid value and 'open' is the default value if the field is missing.
   * @member {String} accessPolicy
   */
  exports.prototype.accessPolicy = undefined;

  return exports;

}));
