/**
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 August, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerakiDashboardApi);
  }
}(this, function(expect, MerakiDashboardApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerakiDashboardApi.Body13();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Body13', function() {
    it('should create an instance of Body13', function() {
      // uncomment below and update the code to test Body13
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be.a(MerakiDashboardApi.Body13);
    });

    it('should have the property dhcpMode (base name: "dhcpMode")', function() {
      // uncomment below and update the code to test the property dhcpMode
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property dhcpRelayServerIps (base name: "dhcpRelayServerIps")', function() {
      // uncomment below and update the code to test the property dhcpRelayServerIps
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property dhcpLeaseTime (base name: "dhcpLeaseTime")', function() {
      // uncomment below and update the code to test the property dhcpLeaseTime
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property dnsNameserversOption (base name: "dnsNameserversOption")', function() {
      // uncomment below and update the code to test the property dnsNameserversOption
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property dnsCustomNameservers (base name: "dnsCustomNameservers")', function() {
      // uncomment below and update the code to test the property dnsCustomNameservers
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property bootOptionsEnabled (base name: "bootOptionsEnabled")', function() {
      // uncomment below and update the code to test the property bootOptionsEnabled
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property bootNextServer (base name: "bootNextServer")', function() {
      // uncomment below and update the code to test the property bootNextServer
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property bootFileName (base name: "bootFileName")', function() {
      // uncomment below and update the code to test the property bootFileName
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property dhcpOptions (base name: "dhcpOptions")', function() {
      // uncomment below and update the code to test the property dhcpOptions
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property reservedIpRanges (base name: "reservedIpRanges")', function() {
      // uncomment below and update the code to test the property reservedIpRanges
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

    it('should have the property fixedIpAssignments (base name: "fixedIpAssignments")', function() {
      // uncomment below and update the code to test the property fixedIpAssignments
      //var instane = new MerakiDashboardApi.Body13();
      //expect(instance).to.be();
    });

  });

}));
