/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerakiDashboardApi);
  }
}(this, function(expect, MerakiDashboardApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('NetworksnetworkIdswitchaccessControlListsRules', function() {
      beforeEach(function() {
        instance = new MerakiDashboardApi.NetworksnetworkIdswitchaccessControlListsRules();
      });

      it('should create an instance of NetworksnetworkIdswitchaccessControlListsRules', function() {
        // TODO: update the code to test NetworksnetworkIdswitchaccessControlListsRules
        expect(instance).to.be.a(MerakiDashboardApi.NetworksnetworkIdswitchaccessControlListsRules);
      });

      it('should have the property comment (base name: "comment")', function() {
        // TODO: update the code to test the property comment
        expect(instance).to.have.property('comment');
        // expect(instance.comment).to.be(expectedValueLiteral);
      });

      it('should have the property policy (base name: "policy")', function() {
        // TODO: update the code to test the property policy
        expect(instance).to.have.property('policy');
        // expect(instance.policy).to.be(expectedValueLiteral);
      });

      it('should have the property ipVersion (base name: "ipVersion")', function() {
        // TODO: update the code to test the property ipVersion
        expect(instance).to.have.property('ipVersion');
        // expect(instance.ipVersion).to.be(expectedValueLiteral);
      });

      it('should have the property protocol (base name: "protocol")', function() {
        // TODO: update the code to test the property protocol
        expect(instance).to.have.property('protocol');
        // expect(instance.protocol).to.be(expectedValueLiteral);
      });

      it('should have the property srcCidr (base name: "srcCidr")', function() {
        // TODO: update the code to test the property srcCidr
        expect(instance).to.have.property('srcCidr');
        // expect(instance.srcCidr).to.be(expectedValueLiteral);
      });

      it('should have the property srcPort (base name: "srcPort")', function() {
        // TODO: update the code to test the property srcPort
        expect(instance).to.have.property('srcPort');
        // expect(instance.srcPort).to.be(expectedValueLiteral);
      });

      it('should have the property dstCidr (base name: "dstCidr")', function() {
        // TODO: update the code to test the property dstCidr
        expect(instance).to.have.property('dstCidr');
        // expect(instance.dstCidr).to.be(expectedValueLiteral);
      });

      it('should have the property dstPort (base name: "dstPort")', function() {
        // TODO: update the code to test the property dstPort
        expect(instance).to.have.property('dstPort');
        // expect(instance.dstPort).to.be(expectedValueLiteral);
      });

      it('should have the property vlan (base name: "vlan")', function() {
        // TODO: update the code to test the property vlan
        expect(instance).to.have.property('vlan');
        // expect(instance.vlan).to.be(expectedValueLiteral);
      });

    });
  });

}));
