/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerakiDashboardApi);
  }
}(this, function(expect, MerakiDashboardApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerakiDashboardApi.AdminsApi();
  });

  describe('(package)', function() {
    describe('AdminsApi', function() {
      describe('createOrganizationAdmin', function() {
        it('should call createOrganizationAdmin successfully', function(done) {
          // TODO: uncomment, update parameter values for createOrganizationAdmin call and complete the assertions
          /*
          var organizationId = "organizationId_example";
          var createOrganizationAdmin = new MerakiDashboardApi.CreateOrganizationAdmin();
          createOrganizationAdmin.email = "";
          createOrganizationAdmin.name = "";
          createOrganizationAdmin.orgAccess = "full";
          createOrganizationAdmin.tags = [new MerakiDashboardApi.OrganizationsorganizationIdadminsTags()];
          createOrganizationAdmin.tags[0].tag = "";
          createOrganizationAdmin.tags[0].access = "full";
          createOrganizationAdmin.networks = [new MerakiDashboardApi.OrganizationsorganizationIdadminsNetworks()];
          createOrganizationAdmin.networks[0].id = "";
          createOrganizationAdmin.networks[0].access = "full";
          createOrganizationAdmin.authenticationMethod = "Email";

          instance.createOrganizationAdmin(organizationId, createOrganizationAdmin, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteOrganizationAdmin', function() {
        it('should call deleteOrganizationAdmin successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteOrganizationAdmin call
          /*
          var organizationId = "organizationId_example";
          var adminId = "adminId_example";

          instance.deleteOrganizationAdmin(organizationId, adminId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getOrganizationAdmins', function() {
        it('should call getOrganizationAdmins successfully', function(done) {
          // TODO: uncomment, update parameter values for getOrganizationAdmins call and complete the assertions
          /*
          var organizationId = "organizationId_example";

          instance.getOrganizationAdmins(organizationId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateOrganizationAdmin', function() {
        it('should call updateOrganizationAdmin successfully', function(done) {
          // TODO: uncomment, update parameter values for updateOrganizationAdmin call and complete the assertions
          /*
          var organizationId = "organizationId_example";
          var adminId = "adminId_example";
          var opts = {};
          opts.updateOrganizationAdmin = new MerakiDashboardApi.UpdateOrganizationAdmin();
          opts.updateOrganizationAdmin.name = "";
          opts.updateOrganizationAdmin.orgAccess = "full";
          opts.updateOrganizationAdmin.tags = [new MerakiDashboardApi.OrganizationsorganizationIdadminsTags()];
          opts.updateOrganizationAdmin.tags[0].tag = "";
          opts.updateOrganizationAdmin.tags[0].access = "full";
          opts.updateOrganizationAdmin.networks = [new MerakiDashboardApi.OrganizationsorganizationIdadminsNetworks()];
          opts.updateOrganizationAdmin.networks[0].id = "";
          opts.updateOrganizationAdmin.networks[0].access = "full";

          instance.updateOrganizationAdmin(organizationId, adminId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
