/*
 * Meraki Dashboard API
 * The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 September, 2020 > > [What's New](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MerakiDashboardApi);
  }
}(this, function(expect, MerakiDashboardApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MerakiDashboardApi.QosRulesApi();
  });

  describe('(package)', function() {
    describe('QosRulesApi', function() {
      describe('createNetworkSwitchQosRule', function() {
        it('should call createNetworkSwitchQosRule successfully', function(done) {
          // TODO: uncomment, update parameter values for createNetworkSwitchQosRule call and complete the assertions
          /*
          var networkId = "networkId_example";
          var createNetworkSwitchQosRule = new MerakiDashboardApi.CreateNetworkSwitchQosRule();
          createNetworkSwitchQosRule.vlan = 0;
          createNetworkSwitchQosRule.protocol = "ANY";
          createNetworkSwitchQosRule.srcPort = 0;
          createNetworkSwitchQosRule.srcPortRange = "";
          createNetworkSwitchQosRule.dstPort = 0;
          createNetworkSwitchQosRule.dstPortRange = "";
          createNetworkSwitchQosRule.dscp = 0;

          instance.createNetworkSwitchQosRule(networkId, createNetworkSwitchQosRule, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteNetworkSwitchQosRule', function() {
        it('should call deleteNetworkSwitchQosRule successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteNetworkSwitchQosRule call
          /*
          var networkId = "networkId_example";
          var qosRuleId = "qosRuleId_example";

          instance.deleteNetworkSwitchQosRule(networkId, qosRuleId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getNetworkSwitchQosRule', function() {
        it('should call getNetworkSwitchQosRule successfully', function(done) {
          // TODO: uncomment, update parameter values for getNetworkSwitchQosRule call and complete the assertions
          /*
          var networkId = "networkId_example";
          var qosRuleId = "qosRuleId_example";

          instance.getNetworkSwitchQosRule(networkId, qosRuleId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getNetworkSwitchQosRules', function() {
        it('should call getNetworkSwitchQosRules successfully', function(done) {
          // TODO: uncomment, update parameter values for getNetworkSwitchQosRules call and complete the assertions
          /*
          var networkId = "networkId_example";

          instance.getNetworkSwitchQosRules(networkId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getNetworkSwitchQosRulesOrder', function() {
        it('should call getNetworkSwitchQosRulesOrder successfully', function(done) {
          // TODO: uncomment, update parameter values for getNetworkSwitchQosRulesOrder call and complete the assertions
          /*
          var networkId = "networkId_example";

          instance.getNetworkSwitchQosRulesOrder(networkId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateNetworkSwitchQosRule', function() {
        it('should call updateNetworkSwitchQosRule successfully', function(done) {
          // TODO: uncomment, update parameter values for updateNetworkSwitchQosRule call and complete the assertions
          /*
          var networkId = "networkId_example";
          var qosRuleId = "qosRuleId_example";
          var opts = {};
          opts.updateNetworkSwitchQosRule = new MerakiDashboardApi.UpdateNetworkSwitchQosRule();
          opts.updateNetworkSwitchQosRule.vlan = 0;
          opts.updateNetworkSwitchQosRule.protocol = "ANY";
          opts.updateNetworkSwitchQosRule.srcPort = 0;
          opts.updateNetworkSwitchQosRule.srcPortRange = "";
          opts.updateNetworkSwitchQosRule.dstPort = 0;
          opts.updateNetworkSwitchQosRule.dstPortRange = "";
          opts.updateNetworkSwitchQosRule.dscp = 0;

          instance.updateNetworkSwitchQosRule(networkId, qosRuleId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateNetworkSwitchQosRulesOrder', function() {
        it('should call updateNetworkSwitchQosRulesOrder successfully', function(done) {
          // TODO: uncomment, update parameter values for updateNetworkSwitchQosRulesOrder call and complete the assertions
          /*
          var networkId = "networkId_example";
          var updateNetworkSwitchQosRulesOrder = new MerakiDashboardApi.UpdateNetworkSwitchQosRulesOrder();
          updateNetworkSwitchQosRulesOrder.ruleIds = [""];

          instance.updateNetworkSwitchQosRulesOrder(networkId, updateNetworkSwitchQosRulesOrder, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
